[package]
name = "bit-visualizer"
version = "0.1.0"
edition = "2021"
authors = ["Akari Harada <akaritwo0two@gmail.com>"]
license = "GPL-3"

[dependencies]
vec-utils = { version = "0.1.0", path = "../vec-utils" }
nestify = "0.3.1"
rayon = "1.10.0"
log = "0.4.1"
env_logger = "0.11.3"
